### ISSUE TITLE
Failing to compile with RNW >= 18

### ISSUE THREAD

**Issue by aurimasmi** [kasinskas/react-native-media-query#11]
Having combination rnmq + rnw >= 18 makes compilation to fail as [this dependency](https://github.com/kasinskas/react-native-media-query/blob/master/utils/create-declaration-block.js#L1) was moved [to different location](https://github.com/necolas/react-native-web/blob/0.18.0/packages/react-native-web/src/exports/StyleSheet/compiler/createReactDOMStyle.js)

**Comment by kasinskas** [comment]
should be fully fixed in 2.0.0
