### ISSUE TITLE
Styles not changing on device rotation

### ISSUE THREAD

**Issue by TheHeumanModean** [kasinskas/react-native-media-query#14]
Is there a built in way to reapply styles after user rotates the device?

I have a simple media query

```
  primary: {
    '@media (min-width: 500px)': {
      justifyContent: "center",
    },
    alignItems: "center",
    display: "flex",
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    marginBottom: 15,
    width: "100%",
  },
```

When I load screen in portrait the styles correctly apply as `justifyContent: "space-between"` but if I rotate the screen that style stays applied even though the width is now greater than 500

If I load in landscape it correctly applies as `justifyContent: "center"` but if I rotate the screen the style stays the same even though now its less than 500

Is there a way for me to handle this outside of subscribing to the device orientation events and changing the styles manually?

**Comment by kasinskas** [comment]
Hey, I assume you're talking about native mobile apps and not the web. If that's the case then for styles to update you will have to rerender the component yourself - there is no built-in way in this package. This was done intentionally not to add unwanted listeners everywhere and let users decide when and what they want to rerender. 

I might have an idea for slightly more optimized hook, but easiest way at the moment would be to just use useWindowDimensions from react-native - 

```js

import { useWindowDimensions } from 'react-native';

const Component = () => {
  useWindowDimensions();

  return (
    <View style={styles.primary}>
         ...
    </View>
  );
};

const {styles} = StyleSheet.create({
  primary: {
    '@media (min-width: 500px)': {
      justifyContent: "center",
    },
    alignItems: "center",
    display: "flex",
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    marginBottom: 15,
    width: "100%",
  }
});
```

**Comment by TheHeumanModean** [comment]
Sound reasoning, thank you!
