### ISSUE TITLE
Use multiple styles into one dataSet

### ISSUE THREAD

**Issue by eimon96** [kasinskas/react-native-media-query#15]
Hello there. I was wondering if there's any way to provide multiple styles into the same dataSet.
For example:

```
 <Text
  style={[ style.text, style.title ]}
  dataSet={{ media: ids.text }}> // how to add ids.title here??
  some text here
</Text>
```

text and title styles both having media query

react-native: 0.70.6
react-native-web: 0.18.0
 react-native-media-query: 2.0.1

**Comment by kasinskas** [comment]
hey, `dataSet={{ media: ids.text + " " + ids.title }}>` (needs to be separated by space) should work

**Comment by eimon96** [comment]
doesn't work unfortunately

**Comment by kasinskas** [comment]
Just tried to reproduce the issue by setting up new test project, seems to be working fine. am i missing anything?

https://github.com/kasinskas/react-native-media-query/assets/22332217/9040b38a-644d-482f-bc4e-8319e9ab880f

**Comment by eimon96** [comment]
I'm sorry my mistake, was trying with empty string without the space ("" instead of " ").

Thanks for sharing the video and thank you very much for your help!
