### ISSUE TITLE
This package is not working

### ISSUE THREAD

**Issue by udemezue01** [kasinskas/react-native-media-query#3]
I tried using this package, on my package and I did not get this to work.

**Comment by kasinskas** [comment]
I'm sorry, but it's hard to understand what is wrong based on what you wrote. Could you elaborate? I'm using this package myself on several projects without any issues.

**Comment by udemezue01** [comment]
I wanted to set the padding based on the media queries, but unfortunately it did not work

**Comment by kasinskas** [comment]
First of all `StyleSheet.create` returns an object that contains ids that are used on web and actual styles.
```js
const {ids, styles} = StyleSheet.create
```
This is mentioned in the readme - https://github.com/kasinskas/react-native-media-query#usage

Secondly, your `@media` rules have the same `max-width`.

**Comment by udemezue01** [comment]
> So what exactly is not working? I assume this is mobile and not web? What's the size of the device and what styles are being applied?

This is react native web, I am developing a web app

**Comment by udemezue01** [comment]
> First of all `StyleSheet.create` returns an object that contains ids that are used on web and actual styles.
> 
> ```js
> const {ids, styles} = StyleSheet.create
> ```
> 
> This is mentioned in the readme - https://github.com/kasinskas/react-native-media-query#usage
> 
> Secondly, your `@media` rules have the same `max-width`.

I will try it out and see, I wanted to have many media query perform various styles.

**Comment by kasinskas** [comment]
> > So what exactly is not working? I assume this is mobile and not web? What's the size of the device and what styles are being applied?
> 
> This is react native web, I am developing a web app

Well then you're also missing `dataSet` (or `data-media` depending on your rn-web version) prop. It's also mentioned in the readme, please have a look.

**Comment by udemezue01** [comment]
Thanks, I will check and get back.
