### ISSUE TITLE
TypeScript Support?

### ISSUE THREAD

**Issue by jamespb97** [kasinskas/react-native-media-query#4]
Are there any plans to add support for typescript?

**Comment by jamespb97** [comment]
Created a pr which has comprehensive type definitions here: https://github.com/kasinskas/react-native-media-query/pull/6

**Comment by kopax-polyconseil** [comment]
Hello, is there any plan to support typescript ? I am reverting but would have loved to use this module. Thanks for sharing !

**Comment by kasinskas** [comment]
it should be supported, thanks to @jamespb97. try 1.0.10
