### ISSUE TITLE
Media Query does not work on the web

### ISSUE THREAD

**Issue by pdaus1405** [kasinskas/react-native-media-query#5]
`item: {
    backgroundColor: 'white',
    '@media (max-width: 1000px)': {
      backgroundColor: 'red',
    },
  },`
  
  background is only on simulators red
  not on mobile web view
  
  any idea why?

**Comment by pdaus1405** [comment]
I think I forgot that
thanks

but the components do not know dataSet in typescript

is this fixed in your PR?

**Comment by kasinskas** [comment]
@pdaus1405 dataSet should be supported in 1.0.10
